### ISSUE TITLE
GECKO rendering tweaks

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/GECKO#2]
In the OLS rendering of GECKO, https://registry.ihccglobal.app/ontologies/gecko

- the ontology IRI is displayed wrongly (even thought the hyperlink seems correct, https://purl.ihccglobal.org/gecko.owl)
- the ontology IRI https://purl.ihccglobal.org/gecko.owl does not resolve
- the license information is not displayed

**Comment by mcourtot** [comment]
Current status: ontology IRI should be http://purl.obolibrary.org/obo/gecko.owl

**Comment by beckyjackson** [comment]
The version of GECKO displayed on OLS is the IHCC view, which is showing up with the correct IRI - http://purl.obolibrary.org/obo/ihcc-gecko.owl

The IRI doesn't resolve correctly, though, because it wasn't added to the PURL configuration. I opened a PR to fix this (OBOFoundry/purl.obolibrary.org#685)

**Comment by beckyjackson** [comment]
Sorry, the IHCC view PURL should be http://purl.obolibrary.org/obo/gecko/ihcc-gecko.owl - I'll fix this in PR #16

**Comment by mcourtot** [comment]
The IRI now resolves. Still missing license info and the version IRI returns a 404

**Comment by jamesaoverton** [comment]
The license is definitely included in the OWL file, and has been for the past six months:

https://github.com/IHCC-cohorts/GECKO/blob/master/gecko.owl#L17

and it shows up correctly on the main OLS:

https://www.ebi.ac.uk/ols/ontologies/gecko

So I suspect a bug with the older version of OLS that we're using.

I made a GitHub release of GECKO as of 2020-12-03 so that the version IRI now resolves:

https://github.com/IHCC-cohorts/GECKO/releases/tag/v2020-12-03

**Comment by jamesaoverton** [comment]
I was wrong: There's no license for the IHCC version of GECKO, which is why it's not showing up in the IHCC OLS. @beckyjackson can you please fix that?
